"""Neutral tool metadata used by routing and tool-preflight observability."""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any, Mapping


@dataclass(frozen=True)
class ToolMetadata:
    """Describe a tool without granting permission or changing invocation policy."""

    capability: str = "unknown"
    source: str = "unknown"
    freshness: str = "unknown"
    side_effect: str = "unknown"
    confirmation: str = "unknown"
    idempotent: str = "unknown"
    nudge_mode: str = "fallback"

    def to_dict(self) -> dict[str, str]:
        """Return JSON-safe metadata for logs and tests."""
        return {
            "capability": self.capability,
            "source": self.source,
            "freshness": self.freshness,
            "side_effect": self.side_effect,
            "confirmation": self.confirmation,
            "idempotent": self.idempotent,
            "nudge_mode": self.nudge_mode,
        }


_KNOWN_TOOL_METADATA: Mapping[str, ToolMetadata] = {
    "get_current_model": ToolMetadata(
        capability="current_model",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "get_current_time": ToolMetadata(
        capability="current_time",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "resolve_relative_dates": ToolMetadata(
        capability="current_time",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "get_dataset_schema": ToolMetadata(
        capability="data_query",
        source="internal_structured_data",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "execute_sql_query": ToolMetadata(
        capability="data_query",
        source="internal_structured_data",
        freshness="dynamic",
        side_effect="read",
        confirmation="policy",
        idempotent="no",
        nudge_mode="evidence",
    ),
    "update_dashboard_context": ToolMetadata(
        capability="dashboard_context",
        source="conversation_context",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "system_http_request": ToolMetadata(
        capability="web_request",
        source="public_web",
        freshness="dynamic",
        side_effect="external_request",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="evidence",
    ),
    "session_status": ToolMetadata(
        capability="session_status",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "get_runtime_capabilities": ToolMetadata(
        capability="runtime_capabilities",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "search_knowledge_base": ToolMetadata(
        capability="knowledge_search",
        source="internal_docs",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "search_qa_examples": ToolMetadata(
        capability="knowledge_search",
        source="internal_docs",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "create_recurring_task": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "get_my_tasks": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "cancel_task": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "start_task": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "pause_task": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "run_task_manually": ToolMetadata(
        capability="task_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "send_dingtalk_message": ToolMetadata(
        capability="notification",
        source="platform_control",
        freshness="current_turn",
        side_effect="external_message",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "send_email": ToolMetadata(
        capability="notification",
        source="platform_control",
        freshness="current_turn",
        side_effect="external_message",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "send_wechat_work_message": ToolMetadata(
        capability="notification",
        source="platform_control",
        freshness="current_turn",
        side_effect="external_message",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "send_feishu_message": ToolMetadata(
        capability="notification",
        source="platform_control",
        freshness="current_turn",
        side_effect="external_message",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "send_portal_notification": ToolMetadata(
        capability="notification",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "jira_search": ToolMetadata(
        capability="jira",
        source="internal_system",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "jira_create_issue": ToolMetadata(
        capability="jira",
        source="internal_system",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "jira_get_projects": ToolMetadata(
        capability="jira",
        source="internal_system",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "list_accessible_datasets": ToolMetadata(
        capability="dataset_catalog",
        source="platform_self_help",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "list_accessible_knowledge_bases": ToolMetadata(
        capability="knowledge_catalog",
        source="platform_self_help",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "list_accessible_directories": ToolMetadata(
        capability="local_file",
        source="runtime_environment",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "excel_document_read": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "excel_document_write": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "word_document_read": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "word_document_write": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "sub_agent_call": ToolMetadata(
        capability="delegation",
        source="internal_agent",
        freshness="dynamic",
        side_effect="delegate",
        confirmation="inherited",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "sub_agent_batch_call": ToolMetadata(
        capability="delegation",
        source="internal_agent",
        freshness="dynamic",
        side_effect="delegate",
        confirmation="inherited",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "todo_write": ToolMetadata(
        capability="task_planning",
        source="platform_control",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "memory_search": ToolMetadata(
        capability="memory_search",
        source="conversation_context",
        freshness="historical",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="special",
    ),
    "request_user_confirmation": ToolMetadata(
        capability="confirmation",
        source="platform_control",
        freshness="current_turn",
        side_effect="control",
        confirmation="ask",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "ask_user_question": ToolMetadata(
        capability="user_question",
        source="platform_control",
        freshness="current_turn",
        side_effect="control",
        confirmation="none",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "Bash": ToolMetadata(
        capability="runtime_tool",
        source="runtime_environment",
        freshness="realtime",
        side_effect="unknown",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="fallback",
    ),
    "read_file": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "read_image": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "write_file": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "search_text": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "exec_command": ToolMetadata(
        capability="runtime_tool",
        source="runtime_environment",
        freshness="realtime",
        side_effect="unknown",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="fallback",
    ),
    "manage_process": ToolMetadata(
        capability="runtime_tool",
        source="runtime_environment",
        freshness="realtime",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "list_process": ToolMetadata(
        capability="runtime_tool",
        source="runtime_environment",
        freshness="realtime",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "create_skills": ToolMetadata(
        capability="skill_management",
        source="platform_control",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "list_available_skills": ToolMetadata(
        capability="skill_catalog",
        source="platform_catalog",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "read_skill_instruction": ToolMetadata(
        capability="skill_management",
        source="platform_control",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "sqlite_scratchpad": ToolMetadata(
        capability="data_query",
        source="conversation_context",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "directory_tree_navigator": ToolMetadata(
        capability="local_file",
        source="runtime_environment",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "web_renderer_and_snapshot": ToolMetadata(
        capability="web_search",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "code_syntax_linter": ToolMetadata(
        capability="code_analysis",
        source="platform_control",
        freshness="current_turn",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "fetch_static_web_url": ToolMetadata(
        capability="web_search",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "web_search_baidu": ToolMetadata(
        capability="web_search",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "web_search_baidu_http": ToolMetadata(
        capability="web_search",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "web_search_bing_http": ToolMetadata(
        capability="web_search",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "update_user_preference": ToolMetadata(
        capability="preference_management",
        source="conversation_context",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "fetch_user_long_term_memory": ToolMetadata(
        capability="memory_search",
        source="conversation_context",
        freshness="historical",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="special",
    ),
    "delete_user_preference": ToolMetadata(
        capability="preference_management",
        source="conversation_context",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "list_available_agents": ToolMetadata(
        capability="agent_catalog",
        source="platform_catalog",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "get_myinfo": ToolMetadata(
        capability="user_profile",
        source="platform_self_help",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "publish_generated_file": ToolMetadata(
        capability="local_file",
        source="user_file",
        freshness="current_turn",
        side_effect="write",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_open": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_snapshot": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_click": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_fill": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_scroll": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_press": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_wait_for": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_select_option": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_read_visible": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_hover": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_drag": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_slider_drag": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_back": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_forward": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_reload": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="external_request",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_tabs": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_switch_tab": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_close_tab": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="session_state",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "browser_upload": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
    "browser_download": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="write",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_export_pdf": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="write",
        confirmation="none",
        idempotent="yes",
        nudge_mode="explicit",
    ),
    "browser_extract_table": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_handle_dialog": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="policy",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_execute_js": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="external_interaction",
        confirmation="ask",
        idempotent="unknown",
        nudge_mode="explicit",
    ),
    "browser_check_auth": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_get_network_logs": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_get_cookies": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="dynamic",
        side_effect="read",
        confirmation="none",
        idempotent="yes",
        nudge_mode="evidence",
    ),
    "browser_set_cookies": ToolMetadata(
        capability="browser",
        source="public_web",
        freshness="current_turn",
        side_effect="write",
        confirmation="ask",
        idempotent="no",
        nudge_mode="explicit",
    ),
}


def resolve_tool_metadata(
    tool: Any,
    *,
    metadata_by_name: Mapping[str, ToolMetadata] | None = None,
) -> ToolMetadata:
    """Resolve explicit metadata and fall back to neutral values."""
    name = str(getattr(tool, "name", tool) or "").strip()
    permission_scope = str(getattr(tool, "permission_scope", "") or "").strip()
    source_type = str(getattr(tool, "source_type", "") or "").strip()
    evidence_types = frozenset(getattr(tool, "evidence_types", None) or ())

    # 运行时权限是工具实例的事实来源，优先级高于按名称推断的历史元数据。
    # 否则，一个动态注册的 POST/写工具只要恰好撞名 execute_sql_query 等已知
    # 只读工具，就会被误标为 evidence，进而触发错误的首步强制调用。
    if permission_scope and permission_scope != "read":
        base_metadata = None
        if metadata_by_name and name in metadata_by_name:
            base_metadata = metadata_by_name[name]
        elif name in _KNOWN_TOOL_METADATA:
            base_metadata = _KNOWN_TOOL_METADATA[name]
        if base_metadata is not None:
            return replace(
                base_metadata,
                side_effect=(
                    "unknown"
                    if base_metadata.side_effect == "read"
                    else base_metadata.side_effect
                ),
                nudge_mode=(
                    "fallback"
                    if base_metadata.nudge_mode == "evidence"
                    else base_metadata.nudge_mode
                ),
            )
        return ToolMetadata(
            source=source_type or "unknown",
            side_effect="unknown",
        )

    if metadata_by_name and name in metadata_by_name:
        return metadata_by_name[name]
    if name in _KNOWN_TOOL_METADATA:
        return _KNOWN_TOOL_METADATA[name]

    if evidence_types and permission_scope == "read":
        return ToolMetadata(
            capability=("external_tool" if source_type in {"mcp", "generic_api"} else "unknown"),
            source=source_type or "unknown",
            freshness="dynamic",
            side_effect="read",
            confirmation="none",
            idempotent="yes",
            nudge_mode="evidence",
        )
    if permission_scope or source_type:
        return ToolMetadata(
            source=source_type or "unknown",
            side_effect=("read" if permission_scope == "read" else "unknown"),
        )
    return ToolMetadata()


__all__ = ["ToolMetadata", "resolve_tool_metadata"]
